let
    Source = #date(2014, 1, 1),
    Custom1 = List.Dates(Source,Number.From(#date(2015,1,1))-Number.From(Source),#duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Custom1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Dates"}}),
    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Dates]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Dates]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Dates]), type text),
    #"Extracted First Characters" = Table.TransformColumns(#"Inserted Month Name", {{"Month Name", each Text.Start(_, 3), type text}}),
    #"Inserted Day" = Table.AddColumn(#"Extracted First Characters", "Day", each Date.Day([Dates]), Int64.Type),
    #"Inserted End of Month" = Table.AddColumn(#"Inserted Day", "End of Month", each Date.EndOfMonth([Dates]), type date),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted End of Month", "Week of Month", each Date.DayOfWeekName([Dates])),
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted Week of Month", "Month/Year", each Text.Combine({[Month Name], Text.From([Year], "en-US")}, "-"), type text),
    #"Extracted First Characters1" = Table.TransformColumns(#"Inserted Merged Column", {{"Week of Month", each Text.Start(_, 3), type text}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Extracted First Characters1",{{"Week of Month", "DayName"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns1", "DayNumber", each Date.DayOfWeek([Dates],1)),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"DayNumber", Int64.Type}})
in
    #"Changed Type1"
